version: '3'
services:
  api:
    image: node:alpine
    environment: 
      PGHOST: db
      PGPORT: 5432
      PGUSER: ${DATABASE_USER}
      PGPASSWORD: ${DATABASE_PASS}
      PGDATABASE: ${DATABASE_NAME}
      PORT: 3000
    ports:
      - 3000:3000
    volumes:
      - type: bind
        source: ./server
        target: /code
    working_dir: /code
    command: sh -c "npm i && npm run dev"
  client:
    image: node:alpine
    ports:
      - 8000:8080
    volumes:
     - type: bind
       source: ./client
       target: /code
    working_dir: /code
    command: sh -c "npm i && npm run dev"
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASS}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - 5432:5432
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ${SEED_FILE_PATH}:/docker-entrypoint-initdb.d/:ro
      - ${SEED_DATA_PATH}:/json/:ro
volumes:
  dbdata:
