version: '3'
services:
  api:
    image: node:alpine
    environment:
      DB_CONNECTION_URI: mongodb://${DATABASE_USER}:${DATABASE_PASS}@db:27017
      DB_NAME: ${DATABASE_NAME}
      DB_COLLECTION_NAME: ${COLLECTION_NAME}
      PORT: 3000
    ports:
      - 3000:3000
      - 5000:5000
    volumes:
      - type: bind
        source: ./server
        target: /code
    working_dir: /code
    command: sh -c "npm i && npm run dev"
  client:
    image: node:alpine
    ports:
      - 8000:8080
    volumes:
     - type: bind
       source: ./client
       target: /code
    working_dir: /code
    command: sh -c "npm i && npm run dev"
  db:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DATABASE_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_PASS}
      MONGO_INITDB_DATABASE: ${DATABASE_NAME}
    volumes:
      - dbdata:/var/lib/mongodb/data
      - ${SEED_FILE_PATH}:/docker-entrypoint-initdb.d/seed.js:ro
  db-seed:
    image: mongo:latest
    depends_on:
      - db
    links:
      - db
    volumes:
      - ${SEED_DATA_PATH}:/seed.json:ro
    command: bash -c "mongoimport --host db --db ${DATABASE_NAME} --collection ${COLLECTION_NAME} --authenticationDatabase admin -u ${DATABASE_USER} -p ${DATABASE_PASS} --file seed.json --jsonArray"   
volumes:
  dbdata:
